### ISSUE TITLE
Something went wrong: unable to call service script.cinema_mode_script with data {'entity_id': None}. 'entity_id' is required

### ISSUE THREAD

**Issue by kamilk91** [jekalmin/extended_openai_conversation#55]
Im not sure what does it mean, which entity_id do i need. 
This script runs without any errors or warnings if i trigger it differently.

It behaves like this with all scripts

**Comment by jekalmin** [comment]
It happens when gpt tries to call "script" service via [execute_services](https://github.com/jekalmin/extended_openai_conversation?tab=readme-ov-file#supported-function-types) function.
The `execute_services` function requires `entity_id` by default.

Workaround:
  - Rather than exposing "script" entities, add a function that calls script instead (see [example](https://github.com/jekalmin/extended_openai_conversation?tab=readme-ov-file#2-2-send-messages-to-another-messenger))

**Comment by jekalmin** [comment]
Closing the issue.
Feel free to reopen it.
