### ISSUE TITLE
Select media_player

### ISSUE THREAD

**Issue by fantnhu** [jekalmin/extended_openai_conversation#61]
Hi! Thank you for your work. Yours is the best custom integration of the year :)
Could you make it so that even in the UI (in your integration) you can select the media_player where it plays the answer? That would be really cool if you could do it with a template option (e.g.: if you are at home, answer on the speakers in the apartment (Google, Amazon...etc). And if away, then the default (on mobile phone where I'm talking to the agent).

I use an M5 Echo, but it has a very bad speaker and we use it a lot at home from our cell phone to talk to the agent. <-- I would like to replace these speakers. 

Some people have already done it uniquely for the original integration, I think you can do it very easily:
[https://github.com/rhasspy/wyoming-satellite/issues/18#event-11319388726
](url)

If there is a possibility to monitor the response with NodeRed and customize it, that would be a very good feature too. If there is one, please let me know!

Thanks again very much for your work!

**Comment by sanderkooger** [comment]
Hey @fantnhu, The only thing this plugin handles is the data being passed to OpenAI and then structuring the response so that home assistant can execute the function. The actual Text to speech is handled by Home Assistant's Wyoming protocol (their voice pipeline). 

You should request this at the home assistant team. They might be able to do it even better By for example having multiple microphones and speakers in multiple rooms, And only play the response TTS in the room where the request originated.
